# Generated by Django 2.2.7 on 2019-12-03 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='webside',
            new_name='website',
        ),
    ]
